// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// cBOmega
arma::mat cBOmega(const NumericMatrix& BBOm0, const NumericMatrix& SSigsr, const NumericMatrix& mmusr);
RcppExport SEXP STAR_cBOmega(SEXP BBOm0SEXP, SEXP SSigsrSEXP, SEXP mmusrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type BBOm0(BBOm0SEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type SSigsr(SSigsrSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type mmusr(mmusrSEXP);
    rcpp_result_gen = Rcpp::wrap(cBOmega(BBOm0, SSigsr, mmusr));
    return rcpp_result_gen;
END_RCPP
}
// cBOmega1
arma::mat cBOmega1(const NumericMatrix& BBOm0, const NumericVector& SSigsr, const NumericMatrix& mmusr);
RcppExport SEXP STAR_cBOmega1(SEXP BBOm0SEXP, SEXP SSigsrSEXP, SEXP mmusrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type BBOm0(BBOm0SEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type SSigsr(SSigsrSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type mmusr(mmusrSEXP);
    rcpp_result_gen = Rcpp::wrap(cBOmega1(BBOm0, SSigsr, mmusr));
    return rcpp_result_gen;
END_RCPP
}
// cBOmegaSimple
arma::mat cBOmegaSimple(const NumericMatrix& BBOm0, const NumericVector& SSigsr, const NumericMatrix& mmusr);
RcppExport SEXP STAR_cBOmegaSimple(SEXP BBOm0SEXP, SEXP SSigsrSEXP, SEXP mmusrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type BBOm0(BBOm0SEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type SSigsr(SSigsrSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type mmusr(mmusrSEXP);
    rcpp_result_gen = Rcpp::wrap(cBOmegaSimple(BBOm0, SSigsr, mmusr));
    return rcpp_result_gen;
END_RCPP
}
// cBOmegaGibbs
arma::mat cBOmegaGibbs(const NumericMatrix& BBOm0, const NumericMatrix& SS2, const NumericMatrix& RR2);
RcppExport SEXP STAR_cBOmegaGibbs(SEXP BBOm0SEXP, SEXP SS2SEXP, SEXP RR2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type BBOm0(BBOm0SEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type SS2(SS2SEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type RR2(RR2SEXP);
    rcpp_result_gen = Rcpp::wrap(cBOmegaGibbs(BBOm0, SS2, RR2));
    return rcpp_result_gen;
END_RCPP
}
// cRoundMatrix
arma::mat cRoundMatrix(const NumericMatrix& XX);
RcppExport SEXP STAR_cRoundMatrix(SEXP XXSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type XX(XXSEXP);
    rcpp_result_gen = Rcpp::wrap(cRoundMatrix(XX));
    return rcpp_result_gen;
END_RCPP
}
// cSumXtX
arma::colvec cSumXtX(const NumericVector& XX);
RcppExport SEXP STAR_cSumXtX(SEXP XXSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type XX(XXSEXP);
    rcpp_result_gen = Rcpp::wrap(cSumXtX(XX));
    return rcpp_result_gen;
END_RCPP
}
// cSumXtXAndDraw
arma::colvec cSumXtXAndDraw(const NumericVector& XX, const double& S2MRt);
RcppExport SEXP STAR_cSumXtXAndDraw(SEXP XXSEXP, SEXP S2MRtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type XX(XXSEXP);
    Rcpp::traits::input_parameter< const double& >::type S2MRt(S2MRtSEXP);
    rcpp_result_gen = Rcpp::wrap(cSumXtXAndDraw(XX, S2MRt));
    return rcpp_result_gen;
END_RCPP
}
// cUnvec
arma::mat cUnvec(const NumericVector& YY);
RcppExport SEXP STAR_cUnvec(SEXP YYSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type YY(YYSEXP);
    rcpp_result_gen = Rcpp::wrap(cUnvec(YY));
    return rcpp_result_gen;
END_RCPP
}
// cUnvecSp
arma::sp_mat cUnvecSp(const NumericVector& YY);
RcppExport SEXP STAR_cUnvecSp(SEXP YYSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type YY(YYSEXP);
    rcpp_result_gen = Rcpp::wrap(cUnvecSp(YY));
    return rcpp_result_gen;
END_RCPP
}
// cUnvecUd
arma::mat cUnvecUd(const NumericVector& YY);
RcppExport SEXP STAR_cUnvecUd(SEXP YYSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type YY(YYSEXP);
    rcpp_result_gen = Rcpp::wrap(cUnvecUd(YY));
    return rcpp_result_gen;
END_RCPP
}
// cUnvecUdSp
arma::sp_mat cUnvecUdSp(const NumericVector& YY);
RcppExport SEXP STAR_cUnvecUdSp(SEXP YYSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type YY(YYSEXP);
    rcpp_result_gen = Rcpp::wrap(cUnvecUdSp(YY));
    return rcpp_result_gen;
END_RCPP
}
// cUpperMRt
double cUpperMRt(const NumericVector& XX);
RcppExport SEXP STAR_cUpperMRt(SEXP XXSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type XX(XXSEXP);
    rcpp_result_gen = Rcpp::wrap(cUpperMRt(XX));
    return rcpp_result_gen;
END_RCPP
}
// cVec
arma::colvec cVec(const NumericMatrix& XX);
RcppExport SEXP STAR_cVec(SEXP XXSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type XX(XXSEXP);
    rcpp_result_gen = Rcpp::wrap(cVec(XX));
    return rcpp_result_gen;
END_RCPP
}
// cVecSp
arma::colvec cVecSp(const arma::sp_mat& XX);
RcppExport SEXP STAR_cVecSp(SEXP XXSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type XX(XXSEXP);
    rcpp_result_gen = Rcpp::wrap(cVecSp(XX));
    return rcpp_result_gen;
END_RCPP
}
// cVecUd
arma::colvec cVecUd(const NumericMatrix& XX);
RcppExport SEXP STAR_cVecUd(SEXP XXSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type XX(XXSEXP);
    rcpp_result_gen = Rcpp::wrap(cVecUd(XX));
    return rcpp_result_gen;
END_RCPP
}
// cVecUdSp
arma::colvec cVecUdSp(const arma::sp_mat& XX);
RcppExport SEXP STAR_cVecUdSp(SEXP XXSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type XX(XXSEXP);
    rcpp_result_gen = Rcpp::wrap(cVecUdSp(XX));
    return rcpp_result_gen;
END_RCPP
}
