# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cBOmega <- function(BBOm0, SSigsr, mmusr) {
    .Call('STAR_cBOmega', PACKAGE = 'STAR', BBOm0, SSigsr, mmusr)
}

cBOmega1 <- function(BBOm0, SSigsr, mmusr) {
    .Call('STAR_cBOmega1', PACKAGE = 'STAR', BBOm0, SSigsr, mmusr)
}

cBOmegaSimple <- function(BBOm0, SSigsr, mmusr) {
    .Call('STAR_cBOmegaSimple', PACKAGE = 'STAR', BBOm0, SSigsr, mmusr)
}

cBOmegaGibbs <- function(BBOm0, SS2, RR2) {
    .Call('STAR_cBOmegaGibbs', PACKAGE = 'STAR', BBOm0, SS2, RR2)
}

cRoundMatrix <- function(XX) {
    .Call('STAR_cRoundMatrix', PACKAGE = 'STAR', XX)
}

cSumXtX <- function(XX) {
    .Call('STAR_cSumXtX', PACKAGE = 'STAR', XX)
}

cSumXtXAndDraw <- function(XX, S2MRt) {
    .Call('STAR_cSumXtXAndDraw', PACKAGE = 'STAR', XX, S2MRt)
}

cUnvec <- function(YY) {
    .Call('STAR_cUnvec', PACKAGE = 'STAR', YY)
}

cUnvecSp <- function(YY) {
    .Call('STAR_cUnvecSp', PACKAGE = 'STAR', YY)
}

cUnvecUd <- function(YY) {
    .Call('STAR_cUnvecUd', PACKAGE = 'STAR', YY)
}

cUnvecUdSp <- function(YY) {
    .Call('STAR_cUnvecUdSp', PACKAGE = 'STAR', YY)
}

cUpperMRt <- function(XX) {
    .Call('STAR_cUpperMRt', PACKAGE = 'STAR', XX)
}

cVec <- function(XX) {
    .Call('STAR_cVec', PACKAGE = 'STAR', XX)
}

cVecSp <- function(XX) {
    .Call('STAR_cVecSp', PACKAGE = 'STAR', XX)
}

cVecUd <- function(XX) {
    .Call('STAR_cVecUd', PACKAGE = 'STAR', XX)
}

cVecUdSp <- function(XX) {
    .Call('STAR_cVecUdSp', PACKAGE = 'STAR', XX)
}

